/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.FileManager;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.LinkedList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author WILMER
 */
public class RolPadre extends javax.swing.JFrame {

    /**
     * Creates new form RolPadre
     */
    private LinkedList<String> identificaciones = new LinkedList<>();

    public RolPadre() {
        initComponents();
        btnSalir.setOpaque(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setBorderPainted(false);
        btnMinimizar.setOpaque(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setBorderPainted(false);
        btnEstudiantes.setOpaque(false);
        btnEstudiantes.setContentAreaFilled(false);
        btnEstudiantes.setBorderPainted(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false);
        btnProfesor.setOpaque(false);
        btnProfesor.setContentAreaFilled(false);
        btnProfesor.setBorderPainted(false);
        btnRegistro.setOpaque(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.setBorderPainted(false);
        btnNoVisible.setOpaque(false);
        btnNoVisible.setContentAreaFilled(false);
        btnNoVisible.setBorderPainted(false);
        btnVisible.setOpaque(false);
        btnVisible.setContentAreaFilled(false);
        btnVisible.setBorderPainted(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/icons/icon.png"));
        this.setIconImage(icono.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnEstudiantes = new javax.swing.JButton();
        btnProfesor = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        txtIdentificacion1 = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtCodigoColegio = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNacimiento = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnVisible = new javax.swing.JButton();
        btnNoVisible = new javax.swing.JButton();
        btnBorrar = new javax.swing.JLabel();
        lblPadre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 12, 50, 50));

        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 10, 50, 50));

        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        btnEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 362, 270, 60));

        btnProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 270, 60));

        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 130, 50));

        txtApellido.setBackground(new java.awt.Color(238, 238, 238));
        txtApellido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtApellido.setBorder(null);
        txtApellido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellido.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 190, 20));

        txtIdentificacion1.setBackground(new java.awt.Color(238, 238, 238));
        txtIdentificacion1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtIdentificacion1.setBorder(null);
        txtIdentificacion1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIdentificacion1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtIdentificacion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdentificacion1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdentificacion1MousePressed(evt);
            }
        });
        txtIdentificacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacion1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdentificacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 430, 20));

        txtNombre.setBackground(new java.awt.Color(238, 238, 238));
        txtNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombre.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 190, 20));

        txtNumero.setBackground(new java.awt.Color(238, 238, 238));
        txtNumero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNumero.setBorder(null);
        txtNumero.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNumero.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroMousePressed(evt);
            }
        });
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 353, 430, 30));

        txtCodigoColegio.setBackground(new java.awt.Color(238, 238, 238));
        txtCodigoColegio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCodigoColegio.setBorder(null);
        txtCodigoColegio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoColegio.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoColegio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoColegioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoColegioMousePressed(evt);
            }
        });
        txtCodigoColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoColegioActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigoColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 413, 430, 30));

        txtCorreo.setBackground(new java.awt.Color(238, 238, 238));
        txtCorreo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCorreo.setBorder(null);
        txtCorreo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCorreo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 473, 430, 30));

        txtNacimiento.setBackground(new java.awt.Color(238, 238, 238));
        txtNacimiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNacimiento.setForeground(new java.awt.Color(204, 204, 204));
        txtNacimiento.setText("DD/MM/AAAA");
        txtNacimiento.setBorder(null);
        txtNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNacimientoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNacimientoMousePressed(evt);
            }
        });
        txtNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 292, 430, 20));

        txtContraseña.setBackground(new java.awt.Color(238, 238, 238));
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 340, 30));

        btnVisible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisibleActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 540, 30, 30));

        btnNoVisible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoVisibleActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 540, 30, 30));

        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 40, 50));

        lblPadre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/registro padre.png"))); // NOI18N
        getContentPane().add(lblPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        RolEstudiante rolEstudiante = new RolEstudiante();
        rolEstudiante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesorActionPerformed
        RolProfesor rolProfesor = new RolProfesor();
        rolProfesor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProfesorActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        Registrar();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed

    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtIdentificacion1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdentificacion1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacion1MousePressed

    private void txtIdentificacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacion1ActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNumeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroMousePressed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtCodigoColegioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoColegioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoColegioMousePressed

    private void txtCodigoColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoColegioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoColegioActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNacimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNacimientoMousePressed
        
    }//GEN-LAST:event_txtNacimientoMousePressed

    private void txtNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacimientoActionPerformed
        
    }//GEN-LAST:event_txtNacimientoActionPerformed

    private void btnVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisibleActionPerformed
        txtContraseña.setEchoChar((char) 0); // Mostrar el texto de la contraseña
    }//GEN-LAST:event_btnVisibleActionPerformed

    private void btnNoVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoVisibleActionPerformed
        txtContraseña.setEchoChar('*'); // Ocultar el texto de la contraseña
    }//GEN-LAST:event_btnNoVisibleActionPerformed

    private void txtIdentificacion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdentificacion1MouseClicked
        txtIdentificacion1.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtIdentificacion1MouseClicked

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        txtNombre.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNacimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNacimientoMouseClicked
        txtNacimiento.setText("");
        txtNacimiento.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNacimientoMouseClicked

    private void txtNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMouseClicked
        txtNumero.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNumeroMouseClicked

    private void txtCodigoColegioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoColegioMouseClicked
        txtCodigoColegio.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtCodigoColegioMouseClicked

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        txtCorreo.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        txtContraseña.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        borrar();
    }//GEN-LAST:event_btnBorrarMouseClicked

    private void borrar() {
    txtApellido.setText("");
    txtCodigoColegio.setText("");
    txtContraseña.setText("");
    txtCorreo.setText("");
    txtIdentificacion1.setText("");
    txtNacimiento.setText("DD/MM/AAAA");
    txtNacimiento.setForeground(Color.LIGHT_GRAY);
    txtNombre.setText("");
    txtNumero.setText("");
}
            
    
    private void Registrar() {
        
        FileManager fileManager = new FileManager("padres.txt");
        
        if (validarDatos()) {
            // Código para registrar los datos
            // Aquí puedes agregar el código necesario para almacenar o procesar los datos
            String contraseña = new String(txtContraseña.getPassword());
            String[] data = new String[]{
                txtIdentificacion1.getText(),
                txtApellido.getText(),
                txtCodigoColegio.getText(),
                contraseña,
                txtCorreo.getText(),            
                txtNacimiento.getText(),
                txtNombre.getText(),
                txtNumero.getText()
            };

            // Aquí agregarías tu lógica de registro, como almacenar los datos en una base de datos
            JOptionPane.showMessageDialog(this, "Registro exitoso!");
            fileManager.saveData(data);
            identificaciones.add(txtIdentificacion1.getText());
            System.out.println(identificaciones);
        } else {
            // Mostrar mensaje de error si los datos no son válidos
            JOptionPane.showMessageDialog(this, "Por favor, ingrese todos los datos correctamente.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        
        }
    }
    
    public boolean validarDatos() {
        // Verificar que todos los campos no estén vacíos
        cargarIdentificacionesDesdeArchivo();
        if (txtApellido.getText().isEmpty() ||
            txtCodigoColegio.getText().isEmpty() ||
            txtContraseña.getPassword().toString().isEmpty() ||
            txtCorreo.getText().isEmpty() ||
            txtIdentificacion1.getText().isEmpty() ||
            txtNacimiento.getText().isEmpty() ||
            txtNombre.getText().isEmpty() ||
            txtNumero.getText().isEmpty()) {
            return false;
        }

        // Validar que el nombre y apellido no contengan números ni símbolos
        if (!validarTexto(txtNombre.getText()) || !validarTexto(txtApellido.getText())) {
            txtNombre.setForeground(Color.RED);
            txtApellido.setForeground(Color.RED);
            return false;
        }

        // Validar formato del correo electrónico
        if (!validarCorreo(txtCorreo.getText())) {
            txtCorreo.setForeground(Color.RED);
            return false;
        }

        // Validar formato de la fecha de nacimiento
        if (!validarFechaNacimiento(txtNacimiento.getText())) {
            txtNacimiento.setForeground(Color.RED);
            return false;
        }

        // Validar que sólo exista una cedula
        if (!verificarIdentificacionNoExiste(txtIdentificacion1.getText())) {
            txtIdentificacion1.setForeground(Color.RED);
            return false;
        }
        
        // Validar que la identificación sea un entero positivo de más de 7 caracteres
        if (!validarIdentificacion(txtIdentificacion1.getText())) {
            txtIdentificacion1.setForeground(Color.RED);
            return false;
        }

        // Validar que el número sea de exactamente 10 dígitos
        if (!validarNumero(txtNumero.getText())) {
            txtNumero.setForeground(Color.RED);
            return false;
        }

        // Validar que el código de colegio sea de exactamente 4 dígitos
        if (!validarCodigoColegio(txtCodigoColegio.getText())) {
            txtCodigoColegio.setForeground(Color.RED);
            return false;
        }

        // Si todos los datos son válidos
        return true;
    }

    private boolean validarCorreo(String correo) {
        // Expresión regular para validar un correo electrónico
        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(correo);
        return matcher.matches();
    }
    
    
    private boolean validarFechaNacimiento(String fecha) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // No permitir fechas inválidas
        try {
            Date date = sdf.parse(fecha);

            // Obtener día, mes y año
            String[] parts = fecha.split("/");
            int day = Integer.parseInt(parts[0]);
            int month = Integer.parseInt(parts[1]);
            int year = Integer.parseInt(parts[2]);

            // Verificar que el mes esté entre 1 y 12
            if (month < 1 || month > 12) {
                return false;
            }

            // Verificar que el día esté entre 1 y 31
            if (day < 1 || day > 31) {
                return false;
            }

            // Verificar el rango del año, que no sea antes de 1900 ni después de 2023
            if (year < 1900 || year > 2023) { 
                return false;
            }

            // Verificar si el año representa a una persona mayor de 18 años
            int currentYear = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
            if ((currentYear - year) < 18) {
                return false;
            }

        } catch (ParseException | NumberFormatException e) {
            return false; // Si ocurre un error al parsear la fecha, la fecha no es válida
        }
        return true;
    }
    private boolean validarIdentificacion(String identificacion) {
        // Verificar que la identificación sea un entero positivo de más de 7 caracteres
        if (identificacion.length() > 7) {
            try {
                int num = Integer.parseInt(identificacion);
                return num > 0; // Es un entero positivo
            } catch (NumberFormatException e) {
                return false; // No es un número válido
            }
        }
        return false; // No tiene más de 7 caracteres
    }
    
    private boolean validarNumero(String numero) {
        // Verificar que el número tenga exactamente 10 dígitos y sea un entero positivo
        if (numero.length() == 10) {
            try {
                Long num = Long.parseLong(numero); // Usamos Long para asegurarnos de que acepte 10 dígitos
                return num > 0; // Es un entero positivo
            } catch (NumberFormatException e) {
                return false; // No es un número válido
            }
        }
        return false; // No tiene exactamente 10 dígitos
    }
    
    private boolean validarTexto(String texto) {
        // Expresión regular para validar que el texto solo contenga letras y espacios
        String textoRegex = "^[a-zA-Z\\s]+$";
        Pattern pattern = Pattern.compile(textoRegex);
        Matcher matcher = pattern.matcher(texto);
        return matcher.matches();
    }
    
    private boolean validarCodigoColegio(String codigo) {
        // Verificar que el código tenga exactamente 4 dígitos y sea un entero positivo
        if (codigo.length() == 4) {
            try {
                int num = Integer.parseInt(codigo);
                if (num > 0) { // Es un entero positivo
                    return codigoExisteEnArchivo(codigo);
                }
            } catch (NumberFormatException e) {
                return false; // No es un número válido
            }
        }
        return false; // No tiene exactamente 4 dígitos
    }

    private boolean codigoExisteEnArchivo(String codigo) {
        try (BufferedReader br = new BufferedReader(new FileReader("codigosColegios.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().equals(codigo)) {
                    return true; // El código existe en el archivo
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false; // El código no se encontró en el archivo
    }

    public void cargarIdentificacionesDesdeArchivo() {
        try (BufferedReader br = new BufferedReader(new FileReader("padres.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                identificaciones.add(line.trim()); // Añadir la identificación a la lista
                // Saltar las siguientes 7 líneas que corresponden a los otros campos del registro
                for (int i = 0; i < 9; i++) {
                    br.readLine();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public boolean verificarIdentificacionNoExiste(String identificacion) {
        return !identificaciones.contains(identificacion);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RolPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RolPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RolPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RolPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RolPadre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBorrar;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnNoVisible;
    private javax.swing.JButton btnProfesor;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVisible;
    private javax.swing.JLabel lblPadre;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigoColegio;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdentificacion1;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
