/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.Display;
import controlador.Config;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static Vista.Seleccion.icono;
import static Vista.Seleccion.apodo;
import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author wfandino
 */
public class Iniciar extends javax.swing.JFrame {

    public static JFrame frame = new JFrame("Flappy Bird");
    public static JFrame app = new JFrame("Geo swim!");
    private Clip clip;
    Color nuevoColor = new Color(100, 113, 192);

    /**
     * Creates new form Iniciar
     */
    public Iniciar() {
        initComponents();
        btnSalir.setOpaque(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setBorderPainted(false);
        btnMinimizar.setOpaque(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setBorderPainted(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false);
        btnTutorial.setOpaque(false);
        btnTutorial.setContentAreaFilled(false);
        btnTutorial.setBorderPainted(false);
        this.setLocationRelativeTo(null);
        ImageIcon iconoApp = new ImageIcon(getClass().getResource("/icons/icon.png"));
        this.setIconImage(iconoApp.getImage());
        perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/"+icono+".png")));
        music();       
        try {
            mostrarDescripcion(apodo);
        } catch (FontFormatException ex) {
            Logger.getLogger(SeleccionIcono.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SeleccionIcono.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void mostrarDescripcion(String apodo) throws FontFormatException, IOException {
        txtDescripcion.setEditable(true);
        Font customFont = Font.createFont(Font.TRUETYPE_FONT, new File("src/font/Schoolbell-Regular.ttf"));
        txtDescripcion.setFont(customFont.deriveFont(Font.PLAIN, 45));
        txtDescripcion.setText(""); // Limpiar el área de texto antes de agregar nueva descripción
        txtDescripcion.setForeground(nuevoColor);
        txtDescripcion.append("¡Que bueno que regresas, \n    "+apodo+"!"); // Agregar la nueva descripción al área de texto
        txtDescripcion.setEditable(false);
    }
    

    public void music() {
        try {
            // Cargar el archivo de audio
            File soundFile = new File("src/controlador/music/menu-opc-2.wav");
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(soundFile));

            // Obtener el control de volumen
            FloatControl volumeControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);

            // Establecer el volumen
            float volume = 0.65f; // 
            float min = volumeControl.getMinimum();
            float max = volumeControl.getMaximum();
            float newVolume = min + (max - min) * volume;
            volumeControl.setValue(newVolume);

            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        btnGeoRace = new javax.swing.JLabel();
        btnSpaceShooter = new javax.swing.JLabel();
        btnFlappyFish = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblNumeros = new javax.swing.JLabel();
        lblFiguras = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        perfil = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnTutorial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("/icons/icon.png").getImage());
        setUndecorated(true);
        setResizable(false);

        root.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGeoRace.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGeoRace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGeoRaceMouseClicked(evt);
            }
        });
        root.add(btnGeoRace, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 490, 160));

        btnSpaceShooter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        root.add(btnSpaceShooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 490, 150));

        btnFlappyFish.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFlappyFish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFlappyFishMouseClicked(evt);
            }
        });
        root.add(btnFlappyFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 490, 160));

        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        root.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 70, 70));

        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        root.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 70, 70));

        lblNumeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNumeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNumerosMouseClicked(evt);
            }
        });
        root.add(lblNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 30, 30));

        lblFiguras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFiguras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFigurasMouseClicked(evt);
            }
        });
        root.add(lblFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 30, 40));

        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        root.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 50));
        root.add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 340, 280));

        scrollDescripcion.setBorder(null);
        scrollDescripcion.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDescripcion.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDescripcion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtDescripcion.setSelectionColor(new java.awt.Color(255, 255, 255));
        scrollDescripcion.setViewportView(txtDescripcion);

        root.add(scrollDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 570, 120));

        btnTutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutorialActionPerformed(evt);
            }
        });
        root.add(btnTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 670, 250, 50));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        root.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 50));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        root.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 60, 50));

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu.png"))); // NOI18N
        root.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeoRaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeoRaceMouseClicked
        clip.stop();
        Display cargame = new Display();
        app.add(cargame);
        app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        app.setSize(500, 720);
        app.setLocationRelativeTo(null);
        app.setUndecorated(true);
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/icons/icon.png"));
        app.setIconImage(icono1.getImage());
        app.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGeoRaceMouseClicked

    private void btnFlappyFishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFlappyFishMouseClicked
        clip.stop();
        frame.setSize(360, 640);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setUndecorated(true);
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/icons/icon.png"));
        frame.setIconImage(icono1.getImage());
        Config config = new Config();
        frame.add(config);
        frame.pack();
        config.requestFocus();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFlappyFishMouseClicked

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lblFigurasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFigurasMouseClicked
        clip.stop();
        Figuras figuras = new Figuras();
        figuras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFigurasMouseClicked

    private void lblNumerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNumerosMouseClicked
        clip.stop();
        Numbers Numbers = new Numbers();
        Numbers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNumerosMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Seleccion seleccion = new Seleccion();
        seleccion.setVisible(true);
        clip.stop();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutorialActionPerformed
        try {
            abrirEnlace("https://www.youtube.com/watch?v=m3K4J-5eR6g");
        } catch (URISyntaxException ex) {
            Logger.getLogger(Iniciar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTutorialActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
// Obtener el control de volumen
        FloatControl volumeControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);        

// Establecer el volumen
        float volume = 0; // 
        float min = volumeControl.getMinimum();
        float max = volumeControl.getMaximum();
        float newVolume = min + (max - min) * volume;
        volumeControl.setValue(newVolume);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // Obtener el control de volumen
        FloatControl volumeControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);

        // Establecer el volumen
        float volume = 0.65f; // 
        float min = volumeControl.getMinimum();
        float max = volumeControl.getMaximum();
        float newVolume = min + (max - min) * volume;
        volumeControl.setValue(newVolume);

    }//GEN-LAST:event_jLabel1MouseClicked

    public static void abrirEnlace(String enlace) throws URISyntaxException {
        try {
            Desktop.getDesktop().browse(new URI(enlace));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }
    
    /*
       JFrame app = new JFrame();
       Display cargame=new Display();
       app.add(cargame);
       app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       app.setSize(500,720);
       app.setLocationRelativeTo(null);
       app.setVisible(true);

        frame.setSize(360, 640);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setUndecorated(true);

        Config config = new Config();
        frame.add(config);
        frame.pack();
        config.requestFocus();
        frame.setVisible(true);    
    
    
    
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnFlappyFish;
    private javax.swing.JLabel btnGeoRace;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel btnSpaceShooter;
    private javax.swing.JButton btnTutorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFiguras;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNumeros;
    private javax.swing.JLabel perfil;
    private javax.swing.JPanel root;
    private javax.swing.JScrollPane scrollDescripcion;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
